import type { Gpu } from "./types";

/**
 * Tracked parts. `query` is what gets sent to each source's search;
 * `match`/`exclude` are case-insensitive regexes applied to listing titles;
 * the [priceMin, priceMax] band throws out accessories, parts and scalps.
 */

const JUNK =
  "water\\s?block|backplate|bracket|cable|adapter|riser|shroud|holder|stand|sticker|figure|box only|shield|laptop|notebook|egpu enclosure";

/** Datacenter searches surface whole servers and 8-GPU boards — keep the bare cards. */
const DC_JUNK = `${JUNK}|barebone|superserver|rackmount|\\b[1248]u\\b|epyc|xeon|motherboard|baseboard|heatsink|tray|8.gpu|4.gpu`;

// List order = chart series order; each order's colors are CVD-validated —
// re-run the palette validator before reordering or adding chartable sources.
const CONSUMER = ["newegg", "central", "ebay", "bestbuy", "microcenter", "bhphoto", "amazon"];
const WORKSTATION = ["newegg", "wiredzone", "central", "ebay", "pcsp", "bhphoto"];
const DATACENTER = ["wiredzone", "newegg", "ebay", "pcsp", "amazon"];

export const GPUS: Gpu[] = [
  {
    slug: "rtx-5090",
    ticker: "RTX-5090",
    name: "GeForce RTX 5090",
    vendor: "NVIDIA",
    category: "consumer",
    vram: "32 GB GDDR7",
    arch: "Blackwell",
    msrp: 1999,
    query: "GeForce RTX 5090",
    match: "rtx\\s?5090",
    exclude: `${JUNK}|5090\\s?d\\b`,
    priceMin: 1900,
    priceMax: 4800,
    sources: CONSUMER,
    blurb:
      "Blackwell flagship. Still selling well above MSRP; the closest thing to a datacenter card you can buy at retail.",
  },
  {
    slug: "rtx-5080",
    ticker: "RTX-5080",
    name: "GeForce RTX 5080",
    vendor: "NVIDIA",
    category: "consumer",
    vram: "16 GB GDDR7",
    arch: "Blackwell",
    msrp: 999,
    query: "GeForce RTX 5080",
    match: "rtx\\s?5080",
    exclude: JUNK,
    priceMin: 850,
    priceMax: 1800,
    sources: CONSUMER,
    blurb:
      "The volume high-end Blackwell part. Street price has been grinding back toward MSRP as supply normalizes.",
  },
  {
    slug: "rtx-5070-ti",
    ticker: "RTX-5070TI",
    name: "GeForce RTX 5070 Ti",
    vendor: "NVIDIA",
    category: "consumer",
    vram: "16 GB GDDR7",
    arch: "Blackwell",
    msrp: 749,
    query: "GeForce RTX 5070 Ti",
    match: "rtx\\s?5070\\s?ti",
    exclude: JUNK,
    priceMin: 620,
    priceMax: 1200,
    sources: CONSUMER,
    blurb:
      "Best perf-per-dollar in the Blackwell stack for 1440p/4K gaming and light local inference.",
  },
  {
    slug: "rtx-4090",
    ticker: "RTX-4090",
    name: "GeForce RTX 4090",
    vendor: "NVIDIA",
    category: "consumer",
    vram: "24 GB GDDR6X",
    arch: "Ada Lovelace",
    msrp: 1599,
    query: "GeForce RTX 4090",
    match: "rtx\\s?4090",
    exclude: `${JUNK}|4090\\s?d\\b`,
    priceMin: 1300,
    priceMax: 3900,
    usedOk: true,
    sources: CONSUMER,
    blurb:
      "Out of production but in demand for local LLM work thanks to 24 GB of VRAM — used prices refuse to fall.",
  },
  {
    slug: "rx-9070-xt",
    ticker: "RX-9070XT",
    name: "Radeon RX 9070 XT",
    vendor: "AMD",
    category: "consumer",
    vram: "16 GB GDDR6",
    arch: "RDNA 4",
    msrp: 599,
    query: "Radeon RX 9070 XT",
    match: "rx\\s?9070\\s?xt",
    exclude: JUNK,
    priceMin: 520,
    priceMax: 1000,
    sources: CONSUMER,
    blurb:
      "RDNA 4 lead part. Strong raster value against the 5070 Ti when street prices dip near MSRP.",
  },
  {
    slug: "rx-7900-xtx",
    ticker: "RX-7900XTX",
    name: "Radeon RX 7900 XTX",
    vendor: "AMD",
    category: "consumer",
    vram: "24 GB GDDR6",
    arch: "RDNA 3",
    msrp: 999,
    query: "Radeon RX 7900 XTX",
    match: "(rx\\s?)?7900\\s?xtx",
    exclude: JUNK,
    priceMin: 600,
    priceMax: 1400,
    sources: CONSUMER,
    blurb:
      "End-of-life RDNA 3 flagship. 24 GB of VRAM under $900 keeps it interesting for budget ROCm inference boxes.",
  },
  {
    slug: "rx-9060-xt",
    ticker: "RX-9060XT",
    name: "Radeon RX 9060 XT",
    vendor: "AMD",
    category: "consumer",
    vram: "16 GB GDDR6",
    arch: "RDNA 4",
    msrp: 349,
    query: "Radeon RX 9060 XT 16GB",
    match: "rx\\s?9060\\s?xt",
    exclude: `${JUNK}|8\\s?gb`,
    priceMin: 280,
    priceMax: 550,
    sources: CONSUMER,
    blurb:
      "The RDNA 4 volume card. 16 GB at a mainstream price makes it the default 1440p pick when it sits near MSRP.",
  },
  {
    slug: "arc-b580",
    ticker: "ARC-B580",
    name: "Intel Arc B580",
    vendor: "Intel",
    category: "consumer",
    vram: "12 GB GDDR6",
    arch: "Battlemage",
    msrp: 249,
    query: "Intel Arc B580",
    match: "\\bb580\\b",
    exclude: JUNK,
    priceMin: 200,
    priceMax: 450,
    sources: CONSUMER,
    blurb:
      "Intel's budget disruptor — 12 GB under $300 when supply cooperates, and the reason entry pricing moved at all this cycle.",
  },
  {
    slug: "rtx-6000-ada",
    ticker: "RTX-6000ADA",
    name: "RTX 6000 Ada Generation",
    vendor: "NVIDIA",
    category: "workstation",
    vram: "48 GB GDDR6 ECC",
    arch: "Ada Lovelace",
    msrp: 6799,
    query: "NVIDIA RTX 6000 Ada",
    match: "rtx\\s?6000\\s?ada",
    exclude: JUNK,
    priceMin: 4200,
    priceMax: 9000,
    sources: WORKSTATION,
    blurb:
      "48 GB workstation card — the quiet workhorse of small fine-tuning rigs that don't need NVLink.",
  },
  {
    slug: "rtx-pro-6000",
    ticker: "PRO-6000BW",
    name: "RTX PRO 6000 Blackwell",
    vendor: "NVIDIA",
    category: "workstation",
    vram: "96 GB GDDR7 ECC",
    arch: "Blackwell",
    msrp: 8565,
    query: "NVIDIA RTX PRO 6000 Blackwell",
    match: "rtx\\s?pro\\s?6000",
    exclude: JUNK,
    priceMin: 6500,
    priceMax: 12500,
    sources: WORKSTATION,
    blurb:
      "96 GB in a workstation slot. The new default for serious local inference without going to the datacenter aisle.",
  },
  {
    slug: "l40s",
    ticker: "L40S",
    name: "NVIDIA L40S",
    vendor: "NVIDIA",
    category: "workstation",
    vram: "48 GB GDDR6 ECC",
    arch: "Ada Lovelace",
    msrp: null,
    query: "NVIDIA L40S",
    match: "\\bl40s\\b",
    exclude: JUNK,
    priceMin: 5000,
    priceMax: 11000,
    sources: WORKSTATION,
    blurb:
      "Passively-cooled server sibling of the 6000 Ada. Popular for inference fleets; priced by negotiation, tracked by street.",
  },
  {
    slug: "v100-32gb",
    ticker: "V100-32G",
    name: "NVIDIA Tesla V100 32GB",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "32 GB HBM2",
    arch: "Volta",
    msrp: null,
    query: "NVIDIA Tesla V100 32GB",
    match: "v100.*32\\s?gb|32\\s?gb.*v100",
    exclude: `${DC_JUNK}|16\\s?gb`,
    priceMin: 400,
    priceMax: 4000,
    usedOk: true,
    sources: DATACENTER,
    blurb:
      "The GPU that trained the first LLM wave, now the cheapest CUDA + HBM ticket in existence. Pure secondary market.",
  },
  {
    slug: "a100-40gb",
    ticker: "A100-40G",
    name: "NVIDIA A100 40GB PCIe",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "40 GB HBM2",
    arch: "Ampere",
    msrp: null,
    query: "NVIDIA A100 40GB",
    match: "a100.*40\\s?gb|40\\s?gb.*a100",
    exclude: `${DC_JUNK}|80\\s?gb`,
    priceMin: 3000,
    priceMax: 12000,
    usedOk: true,
    sources: DATACENTER,
    blurb:
      "The original A100. Half the memory of its 80 GB sibling at well under half the price — the value entry into serious HBM.",
  },
  {
    slug: "a100-80gb",
    ticker: "A100-80G",
    name: "NVIDIA A100 80GB PCIe",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "80 GB HBM2e",
    arch: "Ampere",
    msrp: null,
    query: "NVIDIA A100 80GB",
    match: "a100.*80\\s?gb|80\\s?gb.*a100",
    exclude: `${DC_JUNK}|40\\s?gb`,
    priceMin: 6000,
    priceMax: 22000,
    sources: DATACENTER,
    blurb:
      "The workhorse of the 2021–23 training boom, now flooding the secondary market as fleets upgrade to Hopper.",
  },
  {
    slug: "h100-pcie",
    ticker: "H100-PCIE",
    name: "NVIDIA H100 80GB PCIe",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "80 GB HBM3",
    arch: "Hopper",
    msrp: null,
    query: "NVIDIA H100 80GB PCIe",
    match: "h100",
    exclude: `${DC_JUNK}|nvl|sxm|hgx`,
    priceMin: 15000,
    priceMax: 35000,
    sources: DATACENTER,
    blurb:
      "Hopper in a PCIe slot. Down sharply from the $40k+ panic pricing of 2023, still the liquid benchmark of AI compute.",
  },
  {
    slug: "h100-sxm",
    ticker: "H100-SXM",
    name: "NVIDIA H100 80GB SXM5",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "80 GB HBM3",
    arch: "Hopper",
    msrp: null,
    query: "NVIDIA H100 SXM5",
    match: "h100.*sxm|sxm.*h100",
    exclude: `${DC_JUNK}|nvl|pcie|hgx`,
    priceMin: 18000,
    priceMax: 38000,
    sources: DATACENTER,
    blurb:
      "The SXM module that trained the current generation of frontier models. Trades on 8-way baseboard economics.",
  },
  {
    slug: "h100-nvl",
    ticker: "H100-NVL",
    name: "NVIDIA H100 NVL 94GB",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "94 GB HBM3",
    arch: "Hopper",
    msrp: null,
    query: "NVIDIA H100 NVL",
    match: "h100\\s?nvl",
    exclude: DC_JUNK,
    priceMin: 18000,
    priceMax: 38000,
    sources: DATACENTER,
    blurb:
      "The PCIe pair built for LLM inference — 94 GB per card and NVLink between the two. The H100 you can actually rack without SXM plumbing.",
  },
  {
    slug: "h200",
    ticker: "H200-141G",
    name: "NVIDIA H200 141GB SXM",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "141 GB HBM3e",
    arch: "Hopper",
    msrp: null,
    query: "NVIDIA H200",
    match: "\\bh200\\b",
    exclude: `${DC_JUNK}|nvl|hgx|gh200|grace`,
    priceMin: 22000,
    priceMax: 45000,
    sources: DATACENTER,
    blurb:
      "Hopper with the memory turned up — 141 GB of HBM3e makes it the inference favorite until Blackwell volume lands.",
  },
  {
    slug: "b200",
    ticker: "B200-192G",
    name: "NVIDIA B200 192GB SXM",
    vendor: "NVIDIA",
    category: "datacenter",
    vram: "192 GB HBM3e",
    arch: "Blackwell",
    msrp: null,
    query: "NVIDIA B200",
    match: "\\bb200\\b",
    exclude: `${DC_JUNK}|gb200|grace|hgx|dgx`,
    priceMin: 25000,
    priceMax: 60000,
    sources: DATACENTER,
    blurb:
      "Blackwell's datacenter flagship. Nearly all volume moves inside 8-way systems, so loose modules trade at a premium.",
  },
  {
    slug: "mi300x",
    ticker: "MI300X",
    name: "AMD Instinct MI300X",
    vendor: "AMD",
    category: "datacenter",
    vram: "192 GB HBM3",
    arch: "CDNA 3",
    msrp: null,
    query: "AMD Instinct MI300X",
    match: "mi300x",
    exclude: DC_JUNK,
    priceMin: 8000,
    priceMax: 28000,
    sources: DATACENTER,
    blurb:
      "192 GB per card and an improving ROCm story. The credible second source the market keeps repricing.",
  },
  {
    slug: "mi325x",
    ticker: "MI325X",
    name: "AMD Instinct MI325X",
    vendor: "AMD",
    category: "datacenter",
    vram: "256 GB HBM3e",
    arch: "CDNA 3",
    msrp: null,
    query: "AMD Instinct MI325X",
    match: "mi325x",
    exclude: DC_JUNK,
    priceMin: 9000,
    priceMax: 30000,
    sources: DATACENTER,
    blurb:
      "MI300X with the memory doubled — 256 GB of HBM3e per card, aimed squarely at long-context inference.",
  },
  {
    slug: "mi355x",
    ticker: "MI355X",
    name: "AMD Instinct MI355X",
    vendor: "AMD",
    category: "datacenter",
    vram: "288 GB HBM3e",
    arch: "CDNA 4",
    msrp: null,
    query: "AMD Instinct MI355X",
    match: "mi355x",
    exclude: DC_JUNK,
    priceMin: 15000,
    priceMax: 50000,
    sources: DATACENTER,
    blurb:
      "AMD's current flagship — CDNA 4, 288 GB of HBM3e, and FP4 support. The card AMD is betting the datacenter on.",
  },
  {
    slug: "ascend-910b",
    ticker: "ASC-910B",
    name: "Huawei Ascend 910B",
    vendor: "Huawei",
    category: "datacenter",
    vram: "64 GB HBM2e",
    arch: "Da Vinci",
    msrp: null,
    query: "Huawei Ascend 910B",
    match: "ascend.*910|910b",
    exclude: DC_JUNK,
    priceMin: 4000,
    priceMax: 25000,
    usedOk: true,
    sources: DATACENTER,
    blurb:
      "China's homegrown H100 answer. Rarely surfaces on Western marketplaces — when it does, it prices like a curiosity.",
  },
];

export const gpuBySlug = (slug: string): Gpu | undefined =>
  GPUS.find((g) => g.slug === slug);

export const CATEGORY_LABEL: Record<string, string> = {
  consumer: "Consumer",
  workstation: "Workstation",
  datacenter: "Datacenter AI",
};
